### ISSUE TITLE
[FEATURE] Remove Dependency on gzip_zinfo.c

### ISSUE THREAD

**Issue by dgr237** [awslabs/soci-snapshotter#966] opened 2023-11-28 23:42 UTC
### Description

We are leveraging the soci-snapshotter by baking this functionality into an existing lambda which we have developed for copying images from our on premise registry into ECR. The use of the gzip_zinfo.c library causes issues in being able to run and debug unit tests on non linux based ides e.g. mac or windows.

### Describe the solution you'd like

It would be good if this library could be rewritten in native go code rather than leveraging cgo as this would simplify the testing and debugging of our image copy lambda- At present we have to commit the changes and wait for the lambda to be built and tested on our linux build servers.

**Comment by Kern--** [comment] 2023-11-29 00:14
I think this is a duplicate of https://github.com/awslabs/soci-snapshotter/issues/76. Can you please add your use-case to that issue instead?

**Comment by dgr237** [comment] 2023-11-29 16:02
Sure will do.

Thanks

Dave

**Comment by austinvazquez** [comment] 2023-11-29 16:18
Thanks @dgr237 for adding your use case. Will close this one as duplicate.

**Closed by austinvazquez** 2023-11-29 16:18 UTC
Labels: duplicate, feature
