### ISSUE TITLE
[Bug] Network retries do not honor custom configuration in #499

### ISSUE THREAD

**Issue by sparr** [awslabs/soci-snapshotter#530] opened 2023-03-28 14:31 UTC
### Description

https://github.com/awslabs/soci-snapshotter/pull/499#issuecomment-1481410063 describes the network retry logic using default configuration rather than the provided custom configuration.

### Steps to reproduce the bug

Run the test in that PR

### Describe the results you expected

Retry configuration is honored and test fails sooner.

### Host information

N/A

### Any additional context or information about the bug

This is a time boxed research issue spun off #499 for planning purposes.

**Comment by Kern--** [comment] 2023-03-28 21:20
**1) setting `max_retries = 0` causes 8 retries**
This is expected. The default value of an int is 0 so we assume the value was unset if we see it and use the default 8 retries instead. Otherwise it would be impossible to have a default. We could use a sentinel `-1` to mean "no retries" but some people might expect that to mean "retry forever". I'm not sure there's a good usecase outside of testing for this, though so maybe we can just keep it as is and use 1 retry.

**2) We see 3 retryable requests with 9 attempts each**
I can't reproduce 3, but I do see 2. It seems that the `sh -c times` is not driving any network activity, but `cat /etc/hosts` is driving 2. I'm planning to turn on FUSE access logs to see what's going on there, but I wanted to get clarification if you've added any additional execs to your test or if you're using exactly the code that's in the current revision of the PR @sparr

**Comment by Kern--** [comment] 2023-03-29 18:55
Closed as non-issue. We needed explanations, but these are both expected behavior.

**Closed by Kern--** 2023-03-29 18:55 UTC
Labels: bug
