### ISSUE TITLE
Tune DirectoryCache for pgbench workload

### ISSUE THREAD

**Issue by vkuzniet** [awslabs/soci-snapshotter#203] opened 2022-11-22 19:42 UTC
**Is your feature request related to a problem? Please describe.**
pgbench workload is failing on snapshotter if `direct=true` is not enabled in config.toml (https://github.com/awslabs/soci-snapshotter/blob/714f1a971e676fada47cb4c983b4728d06bab309/cache/cache.go#L78). Asking customers to keep this option always on will steal a benefit of using directory cache to speed up the container workloads. 

**Describe the solution you'd like**
Therefore, the DirectoryCache needs to be tuned/enhanced to do both:
1. Make pgbench workload stable
2. Do not cause performance regression for other workloads.

**Describe alternatives you've considered**
Ask customers  to set `direct=true` for running pgbench.

**Additional context**
N/A

**Comment by Kern--** [comment] 2022-12-13 19:29
First step is to verify that this is an issue.

**Comment by djdongjin** [comment] 2022-12-15 19:59
Based on the discussion with @sbuckfelder, I think we can close this since:

1. The changes (`direct=true`) related to the issue is already enabled by default.
2. From log, pgbench failure seems more related to `aws auth` (somehow aws auth expired/session expired) than memory issue:
  a. Not reproducible.
  b. The failure happens to every run after around 13th run, and it fails directly.
  c. We create branch new containerd/soci process at the beginning of each run. So it shouldn't have accumulated memory/cache.

cc @Kern-- @vkuzniet

**Closed** 2022-12-29 04:57 UTC
Labels: bug, performance
